# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alyvix_object_finder_properties_view.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(583, 291)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(9, 10, 563, 242))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_design = QtGui.QWidget()
        self.tab_design.setObjectName(_fromUtf8("tab_design"))
        self.widget = QtGui.QWidget(self.tab_design)
        self.widget.setGeometry(QtCore.QRect(172, 9, 379, 148))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayoutWidget = QtGui.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 378, 133))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_10 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout.addWidget(self.line_10, 4, 0, 1, 4)
        self.timeout_spinbox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.timeout_spinbox.setMaximum(999999)
        self.timeout_spinbox.setObjectName(_fromUtf8("timeout_spinbox"))
        self.gridLayout.addWidget(self.timeout_spinbox, 2, 3, 1, 1)
        self.namelineedit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.namelineedit.setObjectName(_fromUtf8("namelineedit"))
        self.gridLayout.addWidget(self.namelineedit, 0, 0, 1, 4)
        self.line_3 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 4)
        self.timeout_label = QtGui.QLabel(self.gridLayoutWidget)
        self.timeout_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeout_label.setObjectName(_fromUtf8("timeout_label"))
        self.gridLayout.addWidget(self.timeout_label, 2, 2, 1, 1)
        self.pushButtonEditObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonEditObj.setObjectName(_fromUtf8("pushButtonEditObj"))
        self.gridLayout.addWidget(self.pushButtonEditObj, 5, 2, 1, 1)
        self.pushButtonRemoveObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonRemoveObj.setObjectName(_fromUtf8("pushButtonRemoveObj"))
        self.gridLayout.addWidget(self.pushButtonRemoveObj, 5, 3, 1, 1)
        self.pushButtonSetMainObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonSetMainObj.setObjectName(_fromUtf8("pushButtonSetMainObj"))
        self.gridLayout.addWidget(self.pushButtonSetMainObj, 5, 0, 1, 1)
        self.pushButtonAddSubObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonAddSubObj.setObjectName(_fromUtf8("pushButtonAddSubObj"))
        self.gridLayout.addWidget(self.pushButtonAddSubObj, 5, 1, 1, 1)
        self.timeout_exception = QtGui.QCheckBox(self.gridLayoutWidget)
        self.timeout_exception.setChecked(True)
        self.timeout_exception.setObjectName(_fromUtf8("timeout_exception"))
        self.gridLayout.addWidget(self.timeout_exception, 3, 3, 1, 1)
        self.find_radio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.find_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.find_radio.setObjectName(_fromUtf8("find_radio"))
        self.buttonGroup_5 = QtGui.QButtonGroup(Form)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.find_radio)
        self.gridLayout.addWidget(self.find_radio, 3, 0, 1, 1)
        self.wait_radio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.wait_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wait_radio.setChecked(True)
        self.wait_radio.setObjectName(_fromUtf8("wait_radio"))
        self.buttonGroup_5.addButton(self.wait_radio)
        self.gridLayout.addWidget(self.wait_radio, 2, 0, 1, 1)
        self.wait_disapp_radio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.wait_disapp_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wait_disapp_radio.setChecked(False)
        self.wait_disapp_radio.setObjectName(_fromUtf8("wait_disapp_radio"))
        self.buttonGroup_5.addButton(self.wait_disapp_radio)
        self.gridLayout.addWidget(self.wait_disapp_radio, 2, 1, 1, 1)
        self.listWidget = QtGui.QListWidget(self.tab_design)
        self.listWidget.setGeometry(QtCore.QRect(8, 9, 157, 200))
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.widget_2 = QtGui.QWidget(self.tab_design)
        self.widget_2.setGeometry(QtCore.QRect(173, 310, 378, 100))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.widget_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 376, 96))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.roi_y_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.roi_y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_y_label.setObjectName(_fromUtf8("roi_y_label"))
        self.gridLayout_2.addWidget(self.roi_y_label, 1, 2, 1, 1)
        self.roi_height_spinbox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.roi_height_spinbox.setMaximum(9999)
        self.roi_height_spinbox.setObjectName(_fromUtf8("roi_height_spinbox"))
        self.gridLayout_2.addWidget(self.roi_height_spinbox, 2, 3, 1, 1)
        self.roi_width_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.roi_width_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_width_label.setObjectName(_fromUtf8("roi_width_label"))
        self.gridLayout_2.addWidget(self.roi_width_label, 2, 0, 1, 1)
        self.roi_x_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.roi_x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_x_label.setObjectName(_fromUtf8("roi_x_label"))
        self.gridLayout_2.addWidget(self.roi_x_label, 1, 0, 1, 1)
        self.roi_height_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.roi_height_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_height_label.setObjectName(_fromUtf8("roi_height_label"))
        self.gridLayout_2.addWidget(self.roi_height_label, 2, 2, 1, 1)
        self.roi_width_spinbox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.roi_width_spinbox.setMaximum(9999)
        self.roi_width_spinbox.setObjectName(_fromUtf8("roi_width_spinbox"))
        self.gridLayout_2.addWidget(self.roi_width_spinbox, 2, 1, 1, 1)
        self.roi_x_spinbox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.roi_x_spinbox.setMinimum(-9999)
        self.roi_x_spinbox.setMaximum(9999)
        self.roi_x_spinbox.setObjectName(_fromUtf8("roi_x_spinbox"))
        self.gridLayout_2.addWidget(self.roi_x_spinbox, 1, 1, 1, 1)
        self.roi_y_spinbox = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.roi_y_spinbox.setMinimum(-9999)
        self.roi_y_spinbox.setMaximum(9999)
        self.roi_y_spinbox.setObjectName(_fromUtf8("roi_y_spinbox"))
        self.gridLayout_2.addWidget(self.roi_y_spinbox, 1, 3, 1, 1)
        self.line_7 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 0, 0, 1, 4)
        self.pushButtonEditObj_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonEditObj_2.setObjectName(_fromUtf8("pushButtonEditObj_2"))
        self.gridLayout_2.addWidget(self.pushButtonEditObj_2, 3, 0, 1, 1)
        self.pushButtonRemoveObj_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonRemoveObj_2.setObjectName(_fromUtf8("pushButtonRemoveObj_2"))
        self.gridLayout_2.addWidget(self.pushButtonRemoveObj_2, 3, 2, 1, 1)
        self.pushButtonRoiRedraw = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonRoiRedraw.setObjectName(_fromUtf8("pushButtonRoiRedraw"))
        self.gridLayout_2.addWidget(self.pushButtonRoiRedraw, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_design, _fromUtf8(""))
        self.tab_code = QtGui.QWidget()
        self.tab_code.setObjectName(_fromUtf8("tab_code"))
        self.spinBoxArgs = QtGui.QSpinBox(self.tab_code)
        self.spinBoxArgs.setGeometry(QtCore.QRect(68, 190, 60, 22))
        self.spinBoxArgs.setObjectName(_fromUtf8("spinBoxArgs"))
        self.labelArgs = QtGui.QLabel(self.tab_code)
        self.labelArgs.setGeometry(QtCore.QRect(10, 195, 46, 13))
        self.labelArgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelArgs.setObjectName(_fromUtf8("labelArgs"))
        self.tabWidget.addTab(self.tab_code, _fromUtf8(""))
        self.tab_customlines = QtGui.QWidget()
        self.tab_customlines.setObjectName(_fromUtf8("tab_customlines"))
        self.listWidgetBlocks = QtGui.QListWidget(self.tab_customlines)
        self.listWidgetBlocks.setGeometry(QtCore.QRect(448, 9, 81, 200))
        self.listWidgetBlocks.setObjectName(_fromUtf8("listWidgetBlocks"))
        self.textEditCustomLines = QtGui.QTextEdit(self.tab_customlines)
        self.textEditCustomLines.setGeometry(QtCore.QRect(8, 9, 431, 160))
        self.textEditCustomLines.setTabStopWidth(80)
        self.textEditCustomLines.setAcceptRichText(False)
        self.textEditCustomLines.setObjectName(_fromUtf8("textEditCustomLines"))
        self.pushButtonAddBlock = QtGui.QPushButton(self.tab_customlines)
        self.pushButtonAddBlock.setGeometry(QtCore.QRect(260, 182, 71, 23))
        self.pushButtonAddBlock.setObjectName(_fromUtf8("pushButtonAddBlock"))
        self.spinBoxLine = QtGui.QSpinBox(self.tab_customlines)
        self.spinBoxLine.setGeometry(QtCore.QRect(130, 182, 121, 22))
        self.spinBoxLine.setMinimum(1)
        self.spinBoxLine.setMaximum(99999)
        self.spinBoxLine.setObjectName(_fromUtf8("spinBoxLine"))
        self.label_line = QtGui.QLabel(self.tab_customlines)
        self.label_line.setGeometry(QtCore.QRect(60, 183, 61, 21))
        self.label_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_line.setObjectName(_fromUtf8("label_line"))
        self.pushButtonRemoveBlock = QtGui.QPushButton(self.tab_customlines)
        self.pushButtonRemoveBlock.setGeometry(QtCore.QRect(340, 182, 91, 23))
        self.pushButtonRemoveBlock.setObjectName(_fromUtf8("pushButtonRemoveBlock"))
        self.tabWidget.addTab(self.tab_customlines, _fromUtf8(""))
        self.tab_perfdata = QtGui.QWidget()
        self.tab_perfdata.setObjectName(_fromUtf8("tab_perfdata"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_perfdata)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(19, 10, 497, 61))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBoxEnablePerformance = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBoxEnablePerformance.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxEnablePerformance.setChecked(True)
        self.checkBoxEnablePerformance.setObjectName(_fromUtf8("checkBoxEnablePerformance"))
        self.gridLayout_3.addWidget(self.checkBoxEnablePerformance, 0, 0, 1, 1)
        self.labelCritical = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelCritical.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCritical.setObjectName(_fromUtf8("labelCritical"))
        self.gridLayout_3.addWidget(self.labelCritical, 0, 3, 1, 1)
        self.doubleSpinBoxWarning = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBoxWarning.setMaximum(9999.99)
        self.doubleSpinBoxWarning.setSingleStep(0.05)
        self.doubleSpinBoxWarning.setObjectName(_fromUtf8("doubleSpinBoxWarning"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxWarning, 0, 2, 1, 1)
        self.labelWarning = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelWarning.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWarning.setObjectName(_fromUtf8("labelWarning"))
        self.gridLayout_3.addWidget(self.labelWarning, 0, 1, 1, 1)
        self.doubleSpinBoxCritical = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBoxCritical.setMaximum(9999.99)
        self.doubleSpinBoxCritical.setSingleStep(0.05)
        self.doubleSpinBoxCritical.setObjectName(_fromUtf8("doubleSpinBoxCritical"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxCritical, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tab_perfdata, _fromUtf8(""))
        self.pushButtonOk = QtGui.QPushButton(Form)
        self.pushButtonOk.setGeometry(QtCore.QRect(410, 260, 75, 23))
        self.pushButtonOk.setObjectName(_fromUtf8("pushButtonOk"))
        self.pushButtonCancel = QtGui.QPushButton(Form)
        self.pushButtonCancel.setGeometry(QtCore.QRect(493, 260, 75, 23))
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Alyvix - Object Finder", None))
        self.namelineedit.setText(_translate("Form", "Type here the name of the object", None))
        self.timeout_label.setText(_translate("Form", "Timeout", None))
        self.pushButtonEditObj.setText(_translate("Form", "Edit", None))
        self.pushButtonRemoveObj.setText(_translate("Form", "Remove", None))
        self.pushButtonSetMainObj.setText(_translate("Form", "Set Main Object", None))
        self.pushButtonAddSubObj.setText(_translate("Form", "Add Sub Object", None))
        self.timeout_exception.setText(_translate("Form", "Exception", None))
        self.find_radio.setText(_translate("Form", "Find", None))
        self.wait_radio.setText(_translate("Form", "Wait", None))
        self.wait_disapp_radio.setText(_translate("Form", "Wait Disappear", None))
        self.roi_y_label.setText(_translate("Form", "Roi Y", None))
        self.roi_width_label.setText(_translate("Form", "Roi Width", None))
        self.roi_x_label.setText(_translate("Form", "Roi X", None))
        self.roi_height_label.setText(_translate("Form", "Roi Height", None))
        self.pushButtonEditObj_2.setText(_translate("Form", "Edit", None))
        self.pushButtonRemoveObj_2.setText(_translate("Form", "Remove", None))
        self.pushButtonRoiRedraw.setText(_translate("Form", "Roi Redraw", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_design), _translate("Form", "Graphic Design", None))
        self.labelArgs.setText(_translate("Form", "Args", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_code), _translate("Form", "Source Code", None))
        self.pushButtonAddBlock.setText(_translate("Form", "Add Block", None))
        self.label_line.setText(_translate("Form", "Begin Line", None))
        self.pushButtonRemoveBlock.setText(_translate("Form", "Remove Block", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_customlines), _translate("Form", "Custom Lines", None))
        self.checkBoxEnablePerformance.setText(_translate("Form", "Enable Performance", None))
        self.labelCritical.setText(_translate("Form", "Critical", None))
        self.labelWarning.setText(_translate("Form", "Warning", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_perfdata), _translate("Form", "Performance Data", None))
        self.pushButtonOk.setText(_translate("Form", "Ok", None))
        self.pushButtonCancel.setText(_translate("Form", "Cancel", None))

