# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alyvix_object_finder_properties_view.ui'
#
# Created: Tue Aug  7 16:04:29 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(560, 260)
        self.pushButtonOk = QtGui.QPushButton(Form)
        self.pushButtonOk.setGeometry(QtCore.QRect(393, 230, 75, 23))
        self.pushButtonOk.setObjectName(_fromUtf8("pushButtonOk"))
        self.pushButtonCancel = QtGui.QPushButton(Form)
        self.pushButtonCancel.setGeometry(QtCore.QRect(476, 230, 75, 23))
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.label_line = QtGui.QLabel(Form)
        self.label_line.setGeometry(QtCore.QRect(76, 1027, 61, 21))
        self.label_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_line.setObjectName(_fromUtf8("label_line"))
        self.textEditCustomLines = QtGui.QTextEdit(Form)
        self.textEditCustomLines.setGeometry(QtCore.QRect(24, 853, 431, 160))
        self.textEditCustomLines.setTabStopWidth(80)
        self.textEditCustomLines.setAcceptRichText(False)
        self.textEditCustomLines.setObjectName(_fromUtf8("textEditCustomLines"))
        self.spinBoxLine = QtGui.QSpinBox(Form)
        self.spinBoxLine.setGeometry(QtCore.QRect(146, 1026, 121, 22))
        self.spinBoxLine.setMinimum(1)
        self.spinBoxLine.setMaximum(99999)
        self.spinBoxLine.setObjectName(_fromUtf8("spinBoxLine"))
        self.pushButtonAddBlock = QtGui.QPushButton(Form)
        self.pushButtonAddBlock.setGeometry(QtCore.QRect(276, 1026, 71, 23))
        self.pushButtonAddBlock.setObjectName(_fromUtf8("pushButtonAddBlock"))
        self.pushButtonRemoveBlock = QtGui.QPushButton(Form)
        self.pushButtonRemoveBlock.setGeometry(QtCore.QRect(356, 1026, 91, 23))
        self.pushButtonRemoveBlock.setObjectName(_fromUtf8("pushButtonRemoveBlock"))
        self.listWidgetBlocks = QtGui.QListWidget(Form)
        self.listWidgetBlocks.setGeometry(QtCore.QRect(464, 853, 81, 200))
        self.listWidgetBlocks.setObjectName(_fromUtf8("listWidgetBlocks"))
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(177, 9000, 378, 82))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.widget_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(2, 6, 282, 36))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonEditObj_2 = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButtonEditObj_2.setObjectName(_fromUtf8("pushButtonEditObj_2"))
        self.gridLayout_4.addWidget(self.pushButtonEditObj_2, 0, 2, 1, 1)
        self.pushButtonSetMainObj_2 = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButtonSetMainObj_2.setObjectName(_fromUtf8("pushButtonSetMainObj_2"))
        self.gridLayout_4.addWidget(self.pushButtonSetMainObj_2, 0, 0, 1, 1)
        self.pushButtonAddSubObj_2 = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButtonAddSubObj_2.setObjectName(_fromUtf8("pushButtonAddSubObj_2"))
        self.gridLayout_4.addWidget(self.pushButtonAddSubObj_2, 0, 1, 1, 1)
        self.listWidget = QtGui.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(9, 9, 157, 182))
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(173, 9, 379, 212))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayoutWidget = QtGui.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 378, 195))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonAddSubObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonAddSubObj.setObjectName(_fromUtf8("pushButtonAddSubObj"))
        self.gridLayout.addWidget(self.pushButtonAddSubObj, 5, 1, 1, 1)
        self.pushButtonSetMainObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonSetMainObj.setObjectName(_fromUtf8("pushButtonSetMainObj"))
        self.gridLayout.addWidget(self.pushButtonSetMainObj, 5, 0, 1, 1)
        self.pushButtonEditObj = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonEditObj.setObjectName(_fromUtf8("pushButtonEditObj"))
        self.gridLayout.addWidget(self.pushButtonEditObj, 5, 2, 1, 1)
        self.doubleSpinBoxWarning = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxWarning.setMaximum(9999.99)
        self.doubleSpinBoxWarning.setSingleStep(1.0)
        self.doubleSpinBoxWarning.setObjectName(_fromUtf8("doubleSpinBoxWarning"))
        self.gridLayout.addWidget(self.doubleSpinBoxWarning, 2, 1, 1, 1)
        self.timeout_label = QtGui.QLabel(self.gridLayoutWidget)
        self.timeout_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeout_label.setObjectName(_fromUtf8("timeout_label"))
        self.gridLayout.addWidget(self.timeout_label, 3, 2, 1, 1)
        self.labelCritical = QtGui.QLabel(self.gridLayoutWidget)
        self.labelCritical.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCritical.setObjectName(_fromUtf8("labelCritical"))
        self.gridLayout.addWidget(self.labelCritical, 2, 2, 1, 1)
        self.timeout_exception = QtGui.QCheckBox(self.gridLayoutWidget)
        self.timeout_exception.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.timeout_exception.setChecked(True)
        self.timeout_exception.setObjectName(_fromUtf8("timeout_exception"))
        self.gridLayout.addWidget(self.timeout_exception, 4, 0, 1, 2)
        self.labelWarning = QtGui.QLabel(self.gridLayoutWidget)
        self.labelWarning.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWarning.setObjectName(_fromUtf8("labelWarning"))
        self.gridLayout.addWidget(self.labelWarning, 2, 0, 1, 1)
        self.doubleSpinBoxCritical = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxCritical.setMaximum(9999.99)
        self.doubleSpinBoxCritical.setSingleStep(1.0)
        self.doubleSpinBoxCritical.setObjectName(_fromUtf8("doubleSpinBoxCritical"))
        self.gridLayout.addWidget(self.doubleSpinBoxCritical, 2, 3, 1, 1)
        self.wait_disapp_radio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.wait_disapp_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wait_disapp_radio.setChecked(False)
        self.wait_disapp_radio.setObjectName(_fromUtf8("wait_disapp_radio"))
        self.buttonGroup_5 = QtGui.QButtonGroup(Form)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.wait_disapp_radio)
        self.gridLayout.addWidget(self.wait_disapp_radio, 1, 3, 1, 1)
        self.checkBoxEnablePerformance = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBoxEnablePerformance.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxEnablePerformance.setChecked(True)
        self.checkBoxEnablePerformance.setObjectName(_fromUtf8("checkBoxEnablePerformance"))
        self.gridLayout.addWidget(self.checkBoxEnablePerformance, 4, 2, 1, 2)
        self.timeout_spinbox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.timeout_spinbox.setMaximum(999999)
        self.timeout_spinbox.setObjectName(_fromUtf8("timeout_spinbox"))
        self.gridLayout.addWidget(self.timeout_spinbox, 3, 3, 1, 1)
        self.namelineedit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.namelineedit.setObjectName(_fromUtf8("namelineedit"))
        self.gridLayout.addWidget(self.namelineedit, 0, 1, 1, 3)
        self.wait_radio = QtGui.QRadioButton(self.gridLayoutWidget)
        self.wait_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.wait_radio.setChecked(True)
        self.wait_radio.setObjectName(_fromUtf8("wait_radio"))
        self.buttonGroup_5.addButton(self.wait_radio)
        self.gridLayout.addWidget(self.wait_radio, 1, 0, 1, 3)
        self.labelName = QtGui.QLabel(self.gridLayoutWidget)
        self.labelName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayout.addWidget(self.labelName, 0, 0, 1, 1)
        self.roi_x_label = QtGui.QLabel(Form)
        self.roi_x_label.setGeometry(QtCore.QRect(111, 10000, 89, 20))
        self.roi_x_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_x_label.setObjectName(_fromUtf8("roi_x_label"))
        self.roi_x_spinbox = QtGui.QSpinBox(Form)
        self.roi_x_spinbox.setGeometry(QtCore.QRect(206, 10000, 89, 20))
        self.roi_x_spinbox.setMinimum(-9999)
        self.roi_x_spinbox.setMaximum(9999)
        self.roi_x_spinbox.setObjectName(_fromUtf8("roi_x_spinbox"))
        self.roi_width_spinbox = QtGui.QSpinBox(Form)
        self.roi_width_spinbox.setGeometry(QtCore.QRect(206, 10000, 89, 20))
        self.roi_width_spinbox.setMaximum(9999)
        self.roi_width_spinbox.setObjectName(_fromUtf8("roi_width_spinbox"))
        self.roi_height_spinbox = QtGui.QSpinBox(Form)
        self.roi_height_spinbox.setGeometry(QtCore.QRect(396, 10000, 89, 20))
        self.roi_height_spinbox.setMaximum(9999)
        self.roi_height_spinbox.setObjectName(_fromUtf8("roi_height_spinbox"))
        self.roi_y_label = QtGui.QLabel(Form)
        self.roi_y_label.setGeometry(QtCore.QRect(301, 10000, 89, 20))
        self.roi_y_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_y_label.setObjectName(_fromUtf8("roi_y_label"))
        self.roi_width_label = QtGui.QLabel(Form)
        self.roi_width_label.setGeometry(QtCore.QRect(111, 10000, 89, 20))
        self.roi_width_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_width_label.setObjectName(_fromUtf8("roi_width_label"))
        self.roi_height_label = QtGui.QLabel(Form)
        self.roi_height_label.setGeometry(QtCore.QRect(301, 10000, 89, 20))
        self.roi_height_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roi_height_label.setObjectName(_fromUtf8("roi_height_label"))
        self.roi_y_spinbox = QtGui.QSpinBox(Form)
        self.roi_y_spinbox.setGeometry(QtCore.QRect(396, 10000, 89, 20))
        self.roi_y_spinbox.setMinimum(-9999)
        self.roi_y_spinbox.setMaximum(9999)
        self.roi_y_spinbox.setObjectName(_fromUtf8("roi_y_spinbox"))
        self.labelArgs = QtGui.QLabel(Form)
        self.labelArgs.setGeometry(QtCore.QRect(121, 10000, 90, 20))
        self.labelArgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelArgs.setObjectName(_fromUtf8("labelArgs"))
        self.spinBoxArgs = QtGui.QSpinBox(Form)
        self.spinBoxArgs.setGeometry(QtCore.QRect(217, 10000, 89, 20))
        self.spinBoxArgs.setObjectName(_fromUtf8("spinBoxArgs"))
        self.find_radio = QtGui.QRadioButton(Form)
        self.find_radio.setGeometry(QtCore.QRect(82, 8900, 89, 17))
        self.find_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.find_radio.setObjectName(_fromUtf8("find_radio"))
        self.buttonGroup_5.addButton(self.find_radio)
        self.gridLayoutWidget_3 = QtGui.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 196, 158, 61))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonSelAll = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonSelAll.setObjectName(_fromUtf8("pushButtonSelAll"))
        self.gridLayout_3.addWidget(self.pushButtonSelAll, 0, 0, 1, 1)
        self.pushButtonDesAll = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonDesAll.setObjectName(_fromUtf8("pushButtonDesAll"))
        self.gridLayout_3.addWidget(self.pushButtonDesAll, 0, 1, 1, 1)
        self.pushButtonDelete = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.gridLayout_3.addWidget(self.pushButtonDelete, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Alyvix - Object Finder", None))
        self.pushButtonOk.setText(_translate("Form", "Ok", None))
        self.pushButtonCancel.setText(_translate("Form", "Cancel", None))
        self.label_line.setText(_translate("Form", "Begin Line", None))
        self.pushButtonAddBlock.setText(_translate("Form", "Add Block", None))
        self.pushButtonRemoveBlock.setText(_translate("Form", "Remove Block", None))
        self.pushButtonEditObj_2.setText(_translate("Form", "Edit", None))
        self.pushButtonSetMainObj_2.setText(_translate("Form", "Set Main", None))
        self.pushButtonAddSubObj_2.setText(_translate("Form", "Add Sub", None))
        self.pushButtonAddSubObj.setText(_translate("Form", "Add Sub", None))
        self.pushButtonSetMainObj.setText(_translate("Form", "Set Main", None))
        self.pushButtonEditObj.setText(_translate("Form", "Edit", None))
        self.timeout_label.setText(_translate("Form", "Timeout", None))
        self.labelCritical.setText(_translate("Form", "Critical", None))
        self.timeout_exception.setText(_translate("Form", "Break", None))
        self.labelWarning.setText(_translate("Form", "Warning", None))
        self.wait_disapp_radio.setText(_translate("Form", "Disappeared", None))
        self.checkBoxEnablePerformance.setText(_translate("Form", "Performance", None))
        self.namelineedit.setText(_translate("Form", "Type the keyword name", None))
        self.wait_radio.setText(_translate("Form", "Appeared", None))
        self.labelName.setText(_translate("Form", "Name", None))
        self.roi_x_label.setText(_translate("Form", "Roi X", None))
        self.roi_y_label.setText(_translate("Form", "Roi Y", None))
        self.roi_width_label.setText(_translate("Form", "Roi Width", None))
        self.roi_height_label.setText(_translate("Form", "Roi Height", None))
        self.labelArgs.setText(_translate("Form", "Arguments", None))
        self.find_radio.setText(_translate("Form", "Find", None))
        self.pushButtonSelAll.setText(_translate("Form", "Select All", None))
        self.pushButtonDesAll.setText(_translate("Form", "Deselect All", None))
        self.pushButtonDelete.setText(_translate("Form", "Remove", None))

