# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alyvix_object_selection_view.ui'
#
# Created: Thu May 10 00:17:14 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(457, 329)
        self.pushButtonCC = QtGui.QPushButton(Form)
        self.pushButtonCC.setEnabled(True)
        self.pushButtonCC.setGeometry(QtCore.QRect(9, 9000, 216, 23))
        self.pushButtonCC.setObjectName(_fromUtf8("pushButtonCC"))
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(106, 387, 229, 240))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.widget_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(6, 5, 218, 231))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBoxDelay = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBoxDelay.setMaximum(60)
        self.spinBoxDelay.setObjectName(_fromUtf8("spinBoxDelay"))
        self.gridLayout.addWidget(self.spinBoxDelay, 0, 1, 1, 1)
        self.pushButtonRF = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonRF.setObjectName(_fromUtf8("pushButtonRF"))
        self.gridLayout.addWidget(self.pushButtonRF, 1, 0, 1, 2)
        self.pushButtonIF = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonIF.setObjectName(_fromUtf8("pushButtonIF"))
        self.gridLayout.addWidget(self.pushButtonIF, 2, 0, 1, 2)
        self.pushButtonTF = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonTF.setEnabled(True)
        self.pushButtonTF.setObjectName(_fromUtf8("pushButtonTF"))
        self.gridLayout.addWidget(self.pushButtonTF, 3, 0, 1, 2)
        self.pushButtonOF = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonOF.setEnabled(True)
        self.pushButtonOF.setObjectName(_fromUtf8("pushButtonOF"))
        self.gridLayout.addWidget(self.pushButtonOF, 4, 0, 1, 2)
        self.pushButtonCancel = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.gridLayout.addWidget(self.pushButtonCancel, 5, 0, 1, 2)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 10, 458, 321))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(6, 6, 446, 306))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditSearch = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
        self.gridLayout_2.addWidget(self.lineEditSearch, 0, 0, 1, 3)
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 3)
        self.pushButtonRemove = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonRemove.setObjectName(_fromUtf8("pushButtonRemove"))
        self.gridLayout_2.addWidget(self.pushButtonRemove, 2, 2, 1, 1)
        self.pushButtonEdit = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonEdit.setObjectName(_fromUtf8("pushButtonEdit"))
        self.gridLayout_2.addWidget(self.pushButtonEdit, 2, 1, 1, 1)
        self.pushButtonNew = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonNew.setObjectName(_fromUtf8("pushButtonNew"))
        self.gridLayout_2.addWidget(self.pushButtonNew, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Alyvix - Select Finder", None))
        self.pushButtonCC.setText(_translate("Form", "Custom Code", None))
        self.label_2.setText(_translate("Form", "Delay:", None))
        self.pushButtonRF.setText(_translate("Form", "Rect Finder", None))
        self.pushButtonIF.setText(_translate("Form", "Image Finder", None))
        self.pushButtonTF.setText(_translate("Form", "Text Finder", None))
        self.pushButtonOF.setText(_translate("Form", "Object Finder", None))
        self.pushButtonCancel.setText(_translate("Form", "Cancel", None))
        self.lineEditSearch.setText(_translate("Form", "search...", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Type", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Last Modified", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Name", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "RF", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "15-02-1940", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "ewfdsfdsfsdfdsfdsfsdfs", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "IF", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "15-02-1929", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "citrix_login_to_xamarin_with_a", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButtonRemove.setText(_translate("Form", "Remove", None))
        self.pushButtonEdit.setText(_translate("Form", "Edit", None))
        self.pushButtonNew.setText(_translate("Form", "New", None))

