# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alyvix_object_finder_obj_selection.ui'
#
# Created: Mon Sep 10 10:16:25 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(598, 473)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(1, 5, 595, 468))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(6, 6, 584, 409))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelSpaceUnderSelect = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSpaceUnderSelect.setMinimumSize(QtCore.QSize(0, 0))
        self.labelSpaceUnderSelect.setMaximumSize(QtCore.QSize(16777215, 4))
        self.labelSpaceUnderSelect.setText(_fromUtf8(""))
        self.labelSpaceUnderSelect.setObjectName(_fromUtf8("labelSpaceUnderSelect"))
        self.gridLayout_2.addWidget(self.labelSpaceUnderSelect, 1, 0, 1, 3)
        self.lineEditSearch = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
        self.gridLayout_2.addWidget(self.lineEditSearch, 2, 0, 1, 2)
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/preferences-desktop-theme.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/user-desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/texteffect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/blockdevice-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 3, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 3)
        self.toolButtonCancelText = QtGui.QToolButton(self.gridLayoutWidget_2)
        self.toolButtonCancelText.setStyleSheet(_fromUtf8("border: none;\n"
"background-color: transparent;"))
        self.toolButtonCancelText.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../openicon/open_icon_library-standard-0.11.tar/open_icon_library-standard-0.11/open_icon_library-standard/icons/png/16x16/actions/window-close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCancelText.setIcon(icon4)
        self.toolButtonCancelText.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCancelText.setObjectName(_fromUtf8("toolButtonCancelText"))
        self.gridLayout_2.addWidget(self.toolButtonCancelText, 2, 2, 1, 1)
        self.gridLayoutWidget = QtGui.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(4, 419, 315, 47))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButtonOk = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonOk.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.toolButtonOk.setFont(font)
        self.toolButtonOk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButtonOk.setAutoFillBackground(False)
        self.toolButtonOk.setStyleSheet(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/dialog-ok-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonOk.setIcon(icon5)
        self.toolButtonOk.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonOk.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonOk.setAutoRaise(False)
        self.toolButtonOk.setObjectName(_fromUtf8("toolButtonOk"))
        self.gridLayout.addWidget(self.toolButtonOk, 0, 0, 1, 1)
        self.toolButtonCancel = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonCancel.setMinimumSize(QtCore.QSize(150, 0))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/window-close-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCancel.setIcon(icon6)
        self.toolButtonCancel.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonCancel.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonCancel.setObjectName(_fromUtf8("toolButtonCancel"))
        self.gridLayout.addWidget(self.toolButtonCancel, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Alyvix - Object Selector", None))
        self.lineEditSearch.setText(_translate("Form", "search...", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Type", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date Modified", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "rect", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "RF", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "15-02-1940", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "image", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "IF", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "15-02-1929", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "text", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "TF", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "15-02-1929", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "object", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "OF", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "10-11-2012", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Form", "Select", None))
        self.toolButtonOk.setText(_translate("Form", "Ok", None))
        self.toolButtonCancel.setText(_translate("Form", "Cancel", None))

