# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alyvix_object_selection_view.ui'
#
# Created: Sat Jul 21 22:09:22 2018
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(788, 441)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(1, 5, 786, 434))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(6, 6, 584, 423))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditSearch = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
        self.gridLayout_2.addWidget(self.lineEditSearch, 2, 0, 1, 3)
        self.tableWidget = QtGui.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/preferences-desktop-theme.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/user-desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/texteffect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../images/16x16/blockdevice-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 3, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 3)
        self.gridLayoutWidget = QtGui.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(598, 2, 184, 427))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.toolButtonObjectFinder = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonObjectFinder.setMinimumSize(QtCore.QSize(76, 55))
        font = QtGui.QFont()
        font.setKerning(True)
        self.toolButtonObjectFinder.setFont(font)
        self.toolButtonObjectFinder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButtonObjectFinder.setAutoFillBackground(False)
        self.toolButtonObjectFinder.setStyleSheet(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/blockdevice-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonObjectFinder.setIcon(icon4)
        self.toolButtonObjectFinder.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonObjectFinder.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonObjectFinder.setAutoRaise(False)
        self.toolButtonObjectFinder.setObjectName(_fromUtf8("toolButtonObjectFinder"))
        self.gridLayout.addWidget(self.toolButtonObjectFinder, 4, 2, 1, 1)
        self.toolButtonEdit = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonEdit.setMinimumSize(QtCore.QSize(180, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/preferences-system-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonEdit.setIcon(icon5)
        self.toolButtonEdit.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonEdit.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonEdit.setObjectName(_fromUtf8("toolButtonEdit"))
        self.gridLayout.addWidget(self.toolButtonEdit, 7, 0, 1, 3)
        self.labelArrowDown = QtGui.QLabel(self.gridLayoutWidget)
        self.labelArrowDown.setText(_fromUtf8(""))
        self.labelArrowDown.setPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/arrow32.png")))
        self.labelArrowDown.setObjectName(_fromUtf8("labelArrowDown"))
        self.gridLayout.addWidget(self.labelArrowDown, 3, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 3)
        self.toolButtonRemove = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonRemove.setMinimumSize(QtCore.QSize(180, 0))
        self.toolButtonRemove.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/trash-empty-3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRemove.setIcon(icon6)
        self.toolButtonRemove.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonRemove.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonRemove.setObjectName(_fromUtf8("toolButtonRemove"))
        self.gridLayout.addWidget(self.toolButtonRemove, 8, 0, 1, 3)
        self.toolButtonTextFinder = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonTextFinder.setMinimumSize(QtCore.QSize(76, 0))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/texteffect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonTextFinder.setIcon(icon7)
        self.toolButtonTextFinder.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonTextFinder.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonTextFinder.setObjectName(_fromUtf8("toolButtonTextFinder"))
        self.gridLayout.addWidget(self.toolButtonTextFinder, 5, 0, 1, 1)
        self.toolButtonImageFinder = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonImageFinder.setMinimumSize(QtCore.QSize(76, 0))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/user-desktop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImageFinder.setIcon(icon8)
        self.toolButtonImageFinder.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonImageFinder.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImageFinder.setObjectName(_fromUtf8("toolButtonImageFinder"))
        self.gridLayout.addWidget(self.toolButtonImageFinder, 3, 0, 1, 1)
        self.toolButtonRectFinder = QtGui.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRectFinder.sizePolicy().hasHeightForWidth())
        self.toolButtonRectFinder.setSizePolicy(sizePolicy)
        self.toolButtonRectFinder.setMinimumSize(QtCore.QSize(76, 0))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/preferences-desktop-theme.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRectFinder.setIcon(icon9)
        self.toolButtonRectFinder.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonRectFinder.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonRectFinder.setObjectName(_fromUtf8("toolButtonRectFinder"))
        self.gridLayout.addWidget(self.toolButtonRectFinder, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 3)
        self.labelArrowUp = QtGui.QLabel(self.gridLayoutWidget)
        self.labelArrowUp.setText(_fromUtf8(""))
        self.labelArrowUp.setPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/arrow_up32.png")))
        self.labelArrowUp.setObjectName(_fromUtf8("labelArrowUp"))
        self.gridLayout.addWidget(self.labelArrowUp, 5, 1, 1, 2)
        self.spinBoxDelay = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBoxDelay.setMaximumSize(QtCore.QSize(102, 16777215))
        self.spinBoxDelay.setMaximum(60)
        self.spinBoxDelay.setObjectName(_fromUtf8("spinBoxDelay"))
        self.gridLayout.addWidget(self.spinBoxDelay, 2, 1, 1, 2)
        self.labelArrowRight = QtGui.QLabel(self.gridLayoutWidget)
        self.labelArrowRight.setMaximumSize(QtCore.QSize(25, 16777215))
        self.labelArrowRight.setStyleSheet(_fromUtf8("padding: 0px;"))
        self.labelArrowRight.setText(_fromUtf8(""))
        self.labelArrowRight.setPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/arrow_right32.png")))
        self.labelArrowRight.setObjectName(_fromUtf8("labelArrowRight"))
        self.gridLayout.addWidget(self.labelArrowRight, 4, 1, 1, 1)
        self.toolButtonCancel = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonCancel.setMinimumSize(QtCore.QSize(180, 0))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../images/32x32/window-close-2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCancel.setIcon(icon10)
        self.toolButtonCancel.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonCancel.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonCancel.setObjectName(_fromUtf8("toolButtonCancel"))
        self.gridLayout.addWidget(self.toolButtonCancel, 10, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Alyvix - Select Finder", None))
        self.lineEditSearch.setText(_translate("Form", "search...", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Type", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Date Modified", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "rect", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "RF", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "15-02-1940", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "image", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "IF", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "15-02-1929", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "text", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "TF", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "15-02-1929", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "object", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "OF", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "10-11-2012", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("Form", "Select", None))
        self.toolButtonObjectFinder.setText(_translate("Form", "Object Finder", None))
        self.toolButtonEdit.setText(_translate("Form", "Edit", None))
        self.label_2.setText(_translate("Form", "Delay[s]:", None))
        self.toolButtonRemove.setText(_translate("Form", "Remove", None))
        self.toolButtonTextFinder.setText(_translate("Form", "Text Finder", None))
        self.toolButtonImageFinder.setText(_translate("Form", "Image Finder", None))
        self.toolButtonRectFinder.setText(_translate("Form", "Rect Finder", None))
        self.toolButtonCancel.setText(_translate("Form", "Cancel", None))
        self.label_6.setText(_translate("Form", "Build", None))

